#! python 3
# calculate_product_using_time

import time                                                         # import time module
    
def calcProd():                                                     # create function
    product = 1
    for i in range(1, 10):
        product = product * i                                       # deterimine product for each i
    return product

startTime = time.time()                                             # starting time
prod = calcProd()                                                   # begin calculation
endTime = time.time()                                               # stop time
print('The result is %s digits long.' % (len(str(prod))))           # print statement, result length
print('Took %s seconds to calculate.' % (endTime - startTime))      # print statement, time length)
