#! python 3
# crunchy_gundam - opens the latest episode of Mobile Suit Gundam Wing on CrunchyRoll

from selenium import webdriver                                                                              # import webdriver from selenium package
browser = webdriver.Chrome(executable_path='C://Users/Brian/PycharmProjects/Selenium/chromedriver')         # defines the path to the chromedriver executable
browser.get('https://www.crunchyroll.com/login')                                                            # opens webpage
emailElem = browser.find_element_by_id('login_form_name')                                                   # find email element
emailElem.send_keys('input_email')                                                                          # input email in email bar
passwordElem = browser.find_element_by_id('login_form_password')                                            # find password element
passwordElem.send_keys('input_password')                                                                    # enters password
loginElem = browser.find_element_by_id('login_submit_button')                                               # find login button
loginElem.click()                                                                                           # clicks login button
browser.get('https://www.crunchyroll.com/home/queue')                                                       # opens the queue page
showElem = browser.find_element_by_css_selector('#sortable > li:nth-child(1) > div.queue-item-wrapper > '   # selects Gundam from the queue
                                                'div.container-shadow.hover-classes.queue-item-content > '
                                                'a.anchor-to-episode > div.series-info > '
                                                'span.series-title.ellipsis')
showElem.click()                                                                                            # clicks Gundam, starts episode
fullScreenElem = browser.find_element_by_css_selector('#vilos-player')                                      # finds video element
fullScreenElem.send_keys("f")                                                                               # makes full screen
