#! python3
# filling_out_forms.py

from selenium import webdriver
browser = webdriver.Chrome(executable_path = 'C://Users/Brian/PycharmProjects/Selenium/chromedriver')       # says we will use chrome
browser.get('https://gmail.com')                                                                            # opens gmail
emailElem = browser.find_element_by_id('Email')                                                             # find email element
emailElem.send_keys('your_real_email_here@gmail.com')                                                       # input email in email bar
nextButtonElem = browser.find_element_by_id('next')                                                         # find next button
nextButtonElem.click()                                                                                      # click next button
passwordElem = browser.find_element_by_id('Paaswd')                                                         # find password element
passwordElem.send_keys('your_real_password_here')                                                           # enters password
passwordElem.submit()                                                                                       # submits the information ont he web page
