#! python3
# working_with_direction_keys.py

from selenium import webdriver
from selenium.webdriver.common.keys import Keys
browser = webdriver.Chrome(executable_path = 'C://Users/Brian/PycharmProjects/Selenium/chromedriver')       # says we will use chrome
browser.get('http://nostarch.com')
htmlElem = browser.find_element_by_tag_name('html')                                                         # base tag in html files, useful for the general web page
htmlElem.send_keys(Keys.END)                                                                                # scrolls to the bottom
htmlElem.send_keys(Keys.HOME)                                                                               # scrolls to the top
